### ISSUE TITLE
`npm test` fails on big endian platform

### ISSUE THREAD

**Issue by maximmai** [christkv/bson-ext#30]
The issue was first reported and documented on https://github.com/mongodb/js-bson/issues/73.

Here is the `npm test` output on a SLES12 on IBM z Systems:

```

> bson-ext@0.1.13 test /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv
> nodeunit ./test/node


[1mbson_test[22m
✔ Should Correctly create ObjectID and do deep equals
✔ Should Correctly convert ObjectID to itself
[31m✖ Should Correctly Deserialize object[39m

Error: Child document exceeds parent's bounds
    at Error (native)
    at Object.exports.Should Correctly Deserialize object (/gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/test/node/bson_test.js:135:107)
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/lib/core.js:232:20
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/deps/async.js:168:13
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/deps/async.js:131:25
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/deps/async.js:165:17
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/deps/async.js:463:34
    at Object.exports.setUp (/gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/test/node/bson_test.js:84:3)
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/lib/core.js:260:35
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/deps/async.js:458:21

[31m✖ Should Correctly Deserialize object with all types[39m

Error: Child document exceeds parent's bounds
    at Error (native)
    at Object.exports.Should Correctly Deserialize object with all types (/gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/test/node/bson_test.js:153:107)
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/lib/core.js:232:20
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/deps/async.js:168:13
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/deps/async.js:131:25
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/deps/async.js:165:17
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/deps/async.js:463:34
    at Object.exports.setUp (/gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/test/node/bson_test.js:84:3)
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/lib/core.js:260:35
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/deps/async.js:458:21

✔ Should Serialize and Deserialize String
✔ Should Serialize and Deserialize Empty String
✔ Should Correctly Serialize and Deserialize Integer
✔ Should Correctly Serialize and Deserialize null value
✔ Should Correctly Serialize and Deserialize Number 1
✔ Should Correctly Serialize and Deserialize Object
✔ Should correctly ignore undefined values
{ doc: {}, a: [ 1, 2, null, 3 ] }
✔ Should correctly serialize undefined array entries as null values
✔ Should Correctly Serialize and Deserialize Array
✔ Should Correctly Serialize and Deserialize Buffer
✔ Should Correctly Serialize and Deserialize Number 4
✔ Should Correctly Serialize and Deserialize Array with added on functions
✔ Should correctly deserialize a nested object
✔ Should Correctly Serialize and Deserialize A Boolean
✔ Should Correctly Serialize and Deserialize a Date
✔ Should Correctly Serialize and Deserialize a Date from another VM
✔ Should Correctly Serialize nested doc
✔ Should Correctly Serialize and Deserialize Oid
✔ Should Correctly encode Empty Hash
✔ Should Correctly Serialize and Deserialize Ordered Hash
✔ Should Correctly Serialize and Deserialize Regular Expression
✔ Should Correctly Serialize and Deserialize a Binary object
✔ Should Correctly Serialize and Deserialize a Type 2 Binary object
✔ Should Correctly Serialize and Deserialize a big Binary object
✔ Should Correctly Serialize and Deserialize DBRef
✔ Should Correctly Serialize and Deserialize partial DBRef
✔ Should Correctly Serialize and Deserialize simple Int
✔ Should Correctly Serialize and Deserialize Long Integer
✔ Should Deserialize Large Integers as Number not Long
✔ Should Correctly Serialize and Deserialize Long Integer and Timestamp as different types
✔ Should Always put the id as the first item in a hash
✔ Should Correctly Serialize and Deserialize a User defined Binary object
✔ Should Correclty Serialize and Deserialize a Code object
✔ Should Correctly serialize and deserialize and embedded array
✔ Should Correctly Serialize and Deserialize UTF8
✔ Should Correctly Serialize and Deserialize query object
✔ Should Correctly Serialize and Deserialize empty query object
✔ Should Correctly Serialize and Deserialize array based doc
✔ Should Correctly Serialize and Deserialize Symbol
✔ Should handle Deeply nested document
✔ Should handle complicated all typed object
✔ Should Correctly Serialize Complex Nested Object
✔ Should correctly massive doc
✔ Should Correctly Serialize/Deserialize regexp object
✔ Should Correctly Serialize/Deserialize complicated object
✔ Should Correctly Serialize/Deserialize nested object
✔ Should Correctly Serialize/Deserialize nested object with even more nesting
✔ Should Correctly Serialize empty name object
✔ Should Correctly handle Forced Doubles to ensure we allocate enough space for cap collections
✔ Should deserialize correctly
✔ Should correctly serialize and deserialize MinKey and MaxKey values
✔ Should correctly serialize Double value
✔ ObjectID should correctly create objects
✔ ObjectID should correctly retrieve timestamp
✔ Should Correctly throw error on bsonparser errors
✔ Should correctly calculate the size of a given javascript object
✔ Should correctly calculate the size of a given javascript object using instance method
✔ Should correctly serializeWithBufferAndIndex a given javascript object
✔ Should correctly serializeWithBufferAndIndex a given javascript object using a BSON instance
✔ Should correctly serialize a given javascript object
✔ Should correctly serialize a given javascript object using a bson instance
✔ Should correctly deserialize a buffer using the BSON class level parser
✔ Should correctly deserializeStream a buffer object
✔ ObjectID should have a correct cached representation of the hexString
✔ Should fail to create ObjectID due to illegal hex code
  ---> leak test ... 100/2000
  ---> leak test ... 200/2000
  ---> leak test ... 300/2000
  ---> leak test ... 400/2000
  ---> leak test ... 500/2000
  ---> leak test ... 600/2000
  ---> leak test ... 700/2000
  ---> leak test ... 800/2000
  ---> leak test ... 900/2000
  ---> leak test ... 1000/2000
  ---> leak test ... 1100/2000
  ---> leak test ... 1200/2000
  ---> leak test ... 1300/2000
  ---> leak test ... 1400/2000
  ---> leak test ... 1500/2000
  ---> leak test ... 1600/2000
  ---> leak test ... 1700/2000
  ---> leak test ... 1800/2000
  ---> leak test ... 1900/2000
  ---> leak test ... 2000/2000
  ---> leak test - RSS diff -974848
✔ Should not leak memory

[1mtest_full_bson[22m
[31m✖ Should Correctly Deserialize object with all types[39m

Error: Child document exceeds parent's bounds
    at Error (native)
    at Object.exports.Should Correctly Deserialize object with all types (/gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/test/node/test_full_bson.js:72:21)
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/lib/core.js:232:20
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/deps/async.js:168:13
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/deps/async.js:131:25
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/deps/async.js:165:17
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/deps/async.js:463:34
    at Object.exports.setUp (/gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/test/node/test_full_bson.js:30:3)
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/lib/core.js:260:35
    at /gsa/tlbgsa-h1/10/maximm/mongo-driver/bson-ext.christkv/node_modules/nodeunit/deps/async.js:458:21

✔ Should Serialize and Deserialize String
✔ Should Correctly Serialize and Deserialize Integer
✔ Should Correctly Serialize and Deserialize null value
✔ Should Correctly Serialize and Deserialize undefined value
✔ Should Correctly Serialize and Deserialize Number 3
✔ Should Correctly Serialize and Deserialize Object
✔ Should Correctly Serialize and Deserialize Array
✔ Should Correctly Serialize and Deserialize Array with added on functions
✔ Should Correctly Serialize and Deserialize A Boolean
✔ Should Correctly Serialize and Deserialize a Date
✔ Should Correctly Serialize and Deserialize Oid
✔ Should Correctly Serialize and Deserialize Buffer
✔ Should Correctly encode Empty Hash
✔ Should Correctly Serialize and Deserialize Ordered Hash
✔ Should Correctly Serialize and Deserialize Regular Expression
✔ Should Correctly Serialize and Deserialize a Binary object
✔ Should Correctly Serialize and Deserialize a big Binary object
✔ Should Correctly fail due to attempting serialization of illegal key values

[1mto_bson_test[22m
✔ Should correctly handle toBson function for an object
✔ Should correctly handle embedded toBson function for an object
✔ Should fail when top level object returns a non object type

[1m[31mFAILURES: [39m[22m3/57874 assertions failed (10820ms)
```

**Comment by maximmai** [comment]
@christkv Christ, can you take a look at my PR? Thanks.
