### ISSUE TITLE
TypeError Unknown encoding: 1 with 1.0.2 release

### ISSUE THREAD

**Issue by jmcollin78** [christkv/bson-ext#35]
I ust upgrade to 1.0.2 and my tests give me this error (it was passing with 1.0.1): 
```
Message:
    Unknown encoding: 1
Details:
    domain: [object Object]
    domainThrown: true
Stack:
TypeError: Unknown encoding: 1
    at Buffer.slowToString (buffer.js:487:17)
    at Buffer.toString (buffer.js:500:27)
    at ObjectID.toString (/datas/cld-apps/node_modules/bson-ext/lib/bson/objectid.js:174:20)
    at formatValue (util.js:352:36)
    at formatProperty (util.js:794:15)
    at util.js:654:12
    at Array.map (native)
    at formatObject (util.js:653:15)
    at formatValue (util.js:592:16)
    at formatValue (util.js:358:17)
    at Object.inspect (util.js:186:10)
    at exports.dbg (/datas/cld-apps/packages/system/server/utils/helperDebug.js:13:44)
    at model.<anonymous> (/datas/cld-apps/packages/accounts/server/models/modelAccount.js:324:60)
    at _next (/datas/cld-apps/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/datas/cld-apps/node_modules/hooks-fixed/hooks.js:186:8)
    at model.fn (/datas/cld-apps/node_modules/mongoose/lib/schema.js:223:11)
    at _next (/datas/cld-apps/node_modules/hooks-fixed/hooks.js:62:30)
    at fnWrapper (/datas/cld-apps/node_modules/hooks-fixed/hooks.js:186:8)
    at /datas/cld-apps/node_modules/mongoose/lib/schema.js:198:17
    at /datas/cld-apps/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Edit: reverting to 1.0.1 solve the issue

**Comment by christkv** [comment]
fixed and released in 1.0.4, broken due to early 4.x node Buffer.from throwing on hex encoding.
