### ISSUE TITLE
Error: Map.entries is not a function

### ISSUE THREAD

**Issue by jancurn** [christkv/bson-ext#37]
Yesterday we upgraded bson-ext package from version 0.1.13 to 1.0.4 and started receiving "Error: Map.entries is not a function" when calling serialize(). When we switch to pure JavaScript bson package (version 1.0.4), the problem doesn't happen, so clearly there is an inconsistency between the two implementations. Here's a code to reproduce the problem: 

```javascript
var BSON        = require('bson');
var BSONExt     = require('bson-ext');

var bson = new BSON();
var bsonExt = new BSONExt([BSONExt.Binary, BSONExt.Code, BSONExt.DBRef, BSONExt.Decimal128, BSONExt.Double, BSONExt.Int32, BSONExt.Long, BSONExt.Map, BSONExt.MaxKey, BSONExt.MinKey, BSONExt.ObjectId, BSONExt.BSONRegExp, BSONExt.Symbol, BSONExt.Timestamp]);

var obj = {entries: "test"};

// this one works fine
bson.serialize(obj);

// this throws "Error: Map.entries is not a function"
bsonExt.serialize(obj);
```

Moreover, the problem also occurs in the MongoDB driver (mongodb package version 2.2.20). The following code:

```javascript
var mongo = require('mongodb');
var db;

mongo.MongoClient.connect("MY MONGO URL").then( function(database) {
    db = database;
    console.log("This one works fine");
    return db.collection( 'test' ).insert( {something: "test"} );
}).then( function(database) {
    console.log("This one fails");
    return db.collection( 'test' ).insert( {entries: "test"} );
}).catch( function(err) {
    console.log(err);
});
```

prints the following output (on Mac dev machine):

```
This one works fine
This one fails
libc++abi.dylib: terminating with uncaught exception of type char*
```

On our Linux-based production system the error looks more like this (not sure why is it so different):

```
Error: Map.entries is not a function
    at Error (native)
    at Query.toBin (/home/apifier/worker/node_modules/mongodb-core/lib/connection/commands.js:140:25)
    at Pool.write (/home/apifier/worker/node_modules/mongodb-core/lib/connection/pool.js:923:23)
    at Server.command (/home/apifier/worker/node_modules/mongodb-core/lib/topologies/server.js:516:15)
    at proto.(anonymous function) [as command] (/home/apifier/worker/node_modules/mongodb/lib/apm.js:237:12)
    at Mongos.command (/home/apifier/worker/node_modules/mongodb-core/lib/topologies/mongos.js:840:10)
    at Mongos.command (/home/apifier/worker/node_modules/mongodb/lib/mongos.js:348:17)
    at executeCommand (/home/apifier/worker/node_modules/mongodb/lib/db.js:310:19)
    at Db.command (/home/apifier/worker/node_modules/mongodb/lib/db.js:334:44)
    at wrapped (/home/apifier/worker/node_modules/newrelic/lib/instrumentation/mongodb.js:273:25)
```

**Comment by christkv** [comment]
Released as 1.0.5 will be out in the next 2.2.22 release of the driver. Still have other tickets to resolve first.
